app_directory: /var/www/html

gama_version: 1.9.3
gama_download_url: "https://github.com/gama-platform/gama/releases/download/{{ gama_version }}/GAMA_{{ gama_version }}_Linux.zip"

docker_buildkit: "1"